# Generated by Django 4.2.20 on 2025-03-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentalapp', '0006_alter_carreturn_car_picture_alter_carreturn_rental_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='picture',
        ),
        migrations.AddField(
            model_name='carrental',
            name='car_journey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrental',
            name='car_milege',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrental',
            name='car_registration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='car_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
