# Generated by Django 4.2.20 on 2025-03-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrentalapp', '0007_remove_carrental_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreturn',
            name='rental',
        ),
    ]
