# Generated by Django 4.2.20 on 2025-03-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrentalapp', '0008_remove_carreturn_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrental',
            old_name='time',
            new_name='car_date',
        ),
    ]
